name: telemed_chat
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_callkit_incoming: ^2.0.0+2
  http: ^1.1.0
  lottie: ^2.7.0
  mqtt_client: ^10.0.0
  touch_ripple_effect: ^2.3.0
  uuid: ^4.1.0
  videosdk: ^1.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
